name: GitHub Secrets

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Print the secret value
      run: |
        echo "TOP_SECRET: ${{secrets.TOP_SECRET}}"
        echo "i_am_a_exist: ${{secrets.i_dont_exist}}"

    - name: Print Secret as an enviroment variable
      run: |
        echo "TOP_SECRET: $TOP_SECRET" #TOP_SECRET already set as an env var in the workflow level
      env: 
        AZURE_CREDENTIALS: ${{ secrets.TOP_SECRET }}